#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerekeEnergy.Data_Layer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BKEnergy")]
	public partial class BeEneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertd_device(d_device instance);
    partial void Updated_device(d_device instance);
    partial void Deleted_device(d_device instance);
    partial void Insertd_tariff(d_tariff instance);
    partial void Updated_tariff(d_tariff instance);
    partial void Deleted_tariff(d_tariff instance);
    partial void Insertd_type_device(d_type_device instance);
    partial void Updated_type_device(d_type_device instance);
    partial void Deleted_type_device(d_type_device instance);
    partial void Insertv_testimony(v_testimony instance);
    partial void Updatev_testimony(v_testimony instance);
    partial void Deletev_testimony(v_testimony instance);
    #endregion
		
		public BeEneDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BKEnergyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BeEneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeEneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeEneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeEneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<d_device> d_devices
		{
			get
			{
				return this.GetTable<d_device>();
			}
		}
		
		public System.Data.Linq.Table<d_tariff> d_tariffs
		{
			get
			{
				return this.GetTable<d_tariff>();
			}
		}
		
		public System.Data.Linq.Table<d_type_device> d_type_devices
		{
			get
			{
				return this.GetTable<d_type_device>();
			}
		}
		
		public System.Data.Linq.Table<v_testimony> v_testimonies
		{
			get
			{
				return this.GetTable<v_testimony>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_device")]
	public partial class d_device : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _code;
		
		private string _name;
		
		private int _coefficient;
		
		private System.Nullable<int> _device_id;
		
		private System.Nullable<int> _tariff_Id;
		
		private EntityRef<d_tariff> _d_tariff;
		
		private EntityRef<d_type_device> _d_type_device;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncoefficientChanging(int value);
    partial void OncoefficientChanged();
    partial void Ondevice_idChanging(System.Nullable<int> value);
    partial void Ondevice_idChanged();
    partial void Ontariff_IdChanging(System.Nullable<int> value);
    partial void Ontariff_IdChanged();
    #endregion
		
		public d_device()
		{
			this._d_tariff = default(EntityRef<d_tariff>);
			this._d_type_device = default(EntityRef<d_type_device>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(150)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coefficient", DbType="Int NOT NULL")]
		public int coefficient
		{
			get
			{
				return this._coefficient;
			}
			set
			{
				if ((this._coefficient != value))
				{
					this.OncoefficientChanging(value);
					this.SendPropertyChanging();
					this._coefficient = value;
					this.SendPropertyChanged("coefficient");
					this.OncoefficientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_id", DbType="Int")]
		public System.Nullable<int> device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				if ((this._device_id != value))
				{
					if (this._d_type_device.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondevice_idChanging(value);
					this.SendPropertyChanging();
					this._device_id = value;
					this.SendPropertyChanged("device_id");
					this.Ondevice_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariff_Id", DbType="Int")]
		public System.Nullable<int> tariff_Id
		{
			get
			{
				return this._tariff_Id;
			}
			set
			{
				if ((this._tariff_Id != value))
				{
					if (this._d_tariff.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontariff_IdChanging(value);
					this.SendPropertyChanging();
					this._tariff_Id = value;
					this.SendPropertyChanged("tariff_Id");
					this.Ontariff_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_tariff_d_device", Storage="_d_tariff", ThisKey="tariff_Id", OtherKey="Id", IsForeignKey=true)]
		public d_tariff d_tariff
		{
			get
			{
				return this._d_tariff.Entity;
			}
			set
			{
				d_tariff previousValue = this._d_tariff.Entity;
				if (((previousValue != value) 
							|| (this._d_tariff.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_tariff.Entity = null;
						previousValue.d_devices.Remove(this);
					}
					this._d_tariff.Entity = value;
					if ((value != null))
					{
						value.d_devices.Add(this);
						this._tariff_Id = value.Id;
					}
					else
					{
						this._tariff_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("d_tariff");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_type_device_d_device", Storage="_d_type_device", ThisKey="device_id", OtherKey="Id", IsForeignKey=true)]
		public d_type_device d_type_device
		{
			get
			{
				return this._d_type_device.Entity;
			}
			set
			{
				d_type_device previousValue = this._d_type_device.Entity;
				if (((previousValue != value) 
							|| (this._d_type_device.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_type_device.Entity = null;
						previousValue.d_devices.Remove(this);
					}
					this._d_type_device.Entity = value;
					if ((value != null))
					{
						value.d_devices.Add(this);
						this._device_id = value.Id;
					}
					else
					{
						this._device_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("d_type_device");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_tariff")]
	public partial class d_tariff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private decimal _tariff_1;
		
		private System.Nullable<decimal> _tariff_2;
		
		private System.Nullable<decimal> _tariff_3;
		
		private System.Nullable<decimal> _tariff_4;
		
		private string _code;
		
		private string _name;
		
		private EntitySet<d_device> _d_devices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Ontariff_1Changing(decimal value);
    partial void Ontariff_1Changed();
    partial void Ontariff_2Changing(System.Nullable<decimal> value);
    partial void Ontariff_2Changed();
    partial void Ontariff_3Changing(System.Nullable<decimal> value);
    partial void Ontariff_3Changed();
    partial void Ontariff_4Changing(System.Nullable<decimal> value);
    partial void Ontariff_4Changed();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public d_tariff()
		{
			this._d_devices = new EntitySet<d_device>(new Action<d_device>(this.attach_d_devices), new Action<d_device>(this.detach_d_devices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariff_1", DbType="Decimal(18,2) NOT NULL")]
		public decimal tariff_1
		{
			get
			{
				return this._tariff_1;
			}
			set
			{
				if ((this._tariff_1 != value))
				{
					this.Ontariff_1Changing(value);
					this.SendPropertyChanging();
					this._tariff_1 = value;
					this.SendPropertyChanged("tariff_1");
					this.Ontariff_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariff_2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tariff_2
		{
			get
			{
				return this._tariff_2;
			}
			set
			{
				if ((this._tariff_2 != value))
				{
					this.Ontariff_2Changing(value);
					this.SendPropertyChanging();
					this._tariff_2 = value;
					this.SendPropertyChanged("tariff_2");
					this.Ontariff_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariff_3", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tariff_3
		{
			get
			{
				return this._tariff_3;
			}
			set
			{
				if ((this._tariff_3 != value))
				{
					this.Ontariff_3Changing(value);
					this.SendPropertyChanging();
					this._tariff_3 = value;
					this.SendPropertyChanged("tariff_3");
					this.Ontariff_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariff_4", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tariff_4
		{
			get
			{
				return this._tariff_4;
			}
			set
			{
				if ((this._tariff_4 != value))
				{
					this.Ontariff_4Changing(value);
					this.SendPropertyChanging();
					this._tariff_4 = value;
					this.SendPropertyChanged("tariff_4");
					this.Ontariff_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(150)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_tariff_d_device", Storage="_d_devices", ThisKey="Id", OtherKey="tariff_Id")]
		public EntitySet<d_device> d_devices
		{
			get
			{
				return this._d_devices;
			}
			set
			{
				this._d_devices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_d_devices(d_device entity)
		{
			this.SendPropertyChanging();
			entity.d_tariff = this;
		}
		
		private void detach_d_devices(d_device entity)
		{
			this.SendPropertyChanging();
			entity.d_tariff = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_type_device")]
	public partial class d_type_device : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _code;
		
		private string _name;
		
		private EntitySet<d_device> _d_devices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public d_type_device()
		{
			this._d_devices = new EntitySet<d_device>(new Action<d_device>(this.attach_d_devices), new Action<d_device>(this.detach_d_devices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(150)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_type_device_d_device", Storage="_d_devices", ThisKey="Id", OtherKey="device_id")]
		public EntitySet<d_device> d_devices
		{
			get
			{
				return this._d_devices;
			}
			set
			{
				this._d_devices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_d_devices(d_device entity)
		{
			this.SendPropertyChanging();
			entity.d_type_device = this;
		}
		
		private void detach_d_devices(d_device entity)
		{
			this.SendPropertyChanging();
			entity.d_type_device = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_testimony")]
	public partial class v_testimony : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private decimal _general_T;
		
		private decimal _tt_1;
		
		private decimal _tt_cof_1;
		
		private decimal _amount_tt_cof_1;
		
		private System.Nullable<decimal> _tt_2;
		
		private System.Nullable<decimal> _tt_Cof_2;
		
		private System.Nullable<decimal> _amount_tt_cof_2;
		
		private System.Nullable<decimal> _tt_3;
		
		private System.Nullable<decimal> _tt_cof_3;
		
		private System.Nullable<decimal> _amount_tt_cof_3;
		
		private System.Nullable<decimal> _tt_4;
		
		private System.Nullable<decimal> _tt_cof_4;
		
		private System.Nullable<decimal> _amount_tt_cof_4;
		
		private decimal _total;
		
		private System.DateTime _date_of_testimony;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Ongeneral_TChanging(decimal value);
    partial void Ongeneral_TChanged();
    partial void Ontt_1Changing(decimal value);
    partial void Ontt_1Changed();
    partial void Ontt_cof_1Changing(decimal value);
    partial void Ontt_cof_1Changed();
    partial void Onamount_tt_cof_1Changing(decimal value);
    partial void Onamount_tt_cof_1Changed();
    partial void Ontt_2Changing(System.Nullable<decimal> value);
    partial void Ontt_2Changed();
    partial void Ontt_Cof_2Changing(System.Nullable<decimal> value);
    partial void Ontt_Cof_2Changed();
    partial void Onamount_tt_cof_2Changing(System.Nullable<decimal> value);
    partial void Onamount_tt_cof_2Changed();
    partial void Ontt_3Changing(System.Nullable<decimal> value);
    partial void Ontt_3Changed();
    partial void Ontt_cof_3Changing(System.Nullable<decimal> value);
    partial void Ontt_cof_3Changed();
    partial void Onamount_tt_cof_3Changing(System.Nullable<decimal> value);
    partial void Onamount_tt_cof_3Changed();
    partial void Ontt_4Changing(System.Nullable<decimal> value);
    partial void Ontt_4Changed();
    partial void Ontt_cof_4Changing(System.Nullable<decimal> value);
    partial void Ontt_cof_4Changed();
    partial void Onamount_tt_cof_4Changing(System.Nullable<decimal> value);
    partial void Onamount_tt_cof_4Changed();
    partial void OntotalChanging(decimal value);
    partial void OntotalChanged();
    partial void Ondate_of_testimonyChanging(System.DateTime value);
    partial void Ondate_of_testimonyChanged();
    #endregion
		
		public v_testimony()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_general_T", DbType="Decimal(18,2) NOT NULL")]
		public decimal general_T
		{
			get
			{
				return this._general_T;
			}
			set
			{
				if ((this._general_T != value))
				{
					this.Ongeneral_TChanging(value);
					this.SendPropertyChanging();
					this._general_T = value;
					this.SendPropertyChanged("general_T");
					this.Ongeneral_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_1", DbType="Decimal(18,2) NOT NULL")]
		public decimal tt_1
		{
			get
			{
				return this._tt_1;
			}
			set
			{
				if ((this._tt_1 != value))
				{
					this.Ontt_1Changing(value);
					this.SendPropertyChanging();
					this._tt_1 = value;
					this.SendPropertyChanged("tt_1");
					this.Ontt_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_cof_1", DbType="Decimal(18,2) NOT NULL")]
		public decimal tt_cof_1
		{
			get
			{
				return this._tt_cof_1;
			}
			set
			{
				if ((this._tt_cof_1 != value))
				{
					this.Ontt_cof_1Changing(value);
					this.SendPropertyChanging();
					this._tt_cof_1 = value;
					this.SendPropertyChanged("tt_cof_1");
					this.Ontt_cof_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_tt_cof_1", DbType="Decimal(18,2) NOT NULL")]
		public decimal amount_tt_cof_1
		{
			get
			{
				return this._amount_tt_cof_1;
			}
			set
			{
				if ((this._amount_tt_cof_1 != value))
				{
					this.Onamount_tt_cof_1Changing(value);
					this.SendPropertyChanging();
					this._amount_tt_cof_1 = value;
					this.SendPropertyChanged("amount_tt_cof_1");
					this.Onamount_tt_cof_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tt_2
		{
			get
			{
				return this._tt_2;
			}
			set
			{
				if ((this._tt_2 != value))
				{
					this.Ontt_2Changing(value);
					this.SendPropertyChanging();
					this._tt_2 = value;
					this.SendPropertyChanged("tt_2");
					this.Ontt_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_Cof_2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tt_Cof_2
		{
			get
			{
				return this._tt_Cof_2;
			}
			set
			{
				if ((this._tt_Cof_2 != value))
				{
					this.Ontt_Cof_2Changing(value);
					this.SendPropertyChanging();
					this._tt_Cof_2 = value;
					this.SendPropertyChanged("tt_Cof_2");
					this.Ontt_Cof_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_tt_cof_2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> amount_tt_cof_2
		{
			get
			{
				return this._amount_tt_cof_2;
			}
			set
			{
				if ((this._amount_tt_cof_2 != value))
				{
					this.Onamount_tt_cof_2Changing(value);
					this.SendPropertyChanging();
					this._amount_tt_cof_2 = value;
					this.SendPropertyChanged("amount_tt_cof_2");
					this.Onamount_tt_cof_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_3", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tt_3
		{
			get
			{
				return this._tt_3;
			}
			set
			{
				if ((this._tt_3 != value))
				{
					this.Ontt_3Changing(value);
					this.SendPropertyChanging();
					this._tt_3 = value;
					this.SendPropertyChanged("tt_3");
					this.Ontt_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_cof_3", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tt_cof_3
		{
			get
			{
				return this._tt_cof_3;
			}
			set
			{
				if ((this._tt_cof_3 != value))
				{
					this.Ontt_cof_3Changing(value);
					this.SendPropertyChanging();
					this._tt_cof_3 = value;
					this.SendPropertyChanged("tt_cof_3");
					this.Ontt_cof_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_tt_cof_3", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> amount_tt_cof_3
		{
			get
			{
				return this._amount_tt_cof_3;
			}
			set
			{
				if ((this._amount_tt_cof_3 != value))
				{
					this.Onamount_tt_cof_3Changing(value);
					this.SendPropertyChanging();
					this._amount_tt_cof_3 = value;
					this.SendPropertyChanged("amount_tt_cof_3");
					this.Onamount_tt_cof_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_4", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tt_4
		{
			get
			{
				return this._tt_4;
			}
			set
			{
				if ((this._tt_4 != value))
				{
					this.Ontt_4Changing(value);
					this.SendPropertyChanging();
					this._tt_4 = value;
					this.SendPropertyChanged("tt_4");
					this.Ontt_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_cof_4", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tt_cof_4
		{
			get
			{
				return this._tt_cof_4;
			}
			set
			{
				if ((this._tt_cof_4 != value))
				{
					this.Ontt_cof_4Changing(value);
					this.SendPropertyChanging();
					this._tt_cof_4 = value;
					this.SendPropertyChanged("tt_cof_4");
					this.Ontt_cof_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_tt_cof_4", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> amount_tt_cof_4
		{
			get
			{
				return this._amount_tt_cof_4;
			}
			set
			{
				if ((this._amount_tt_cof_4 != value))
				{
					this.Onamount_tt_cof_4Changing(value);
					this.SendPropertyChanging();
					this._amount_tt_cof_4 = value;
					this.SendPropertyChanged("amount_tt_cof_4");
					this.Onamount_tt_cof_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2) NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_testimony", DbType="DateTime NOT NULL")]
		public System.DateTime date_of_testimony
		{
			get
			{
				return this._date_of_testimony;
			}
			set
			{
				if ((this._date_of_testimony != value))
				{
					this.Ondate_of_testimonyChanging(value);
					this.SendPropertyChanging();
					this._date_of_testimony = value;
					this.SendPropertyChanged("date_of_testimony");
					this.Ondate_of_testimonyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
